"""Golden partitions pinned from the finders (PR-C behavior-identity net).

Every literal below was generated by running the finders as of the commit
that introduced this file (scripts kept in the session scratchpad). The
PR-C refactor (proposer protocol, direct Partition construction, tree.py
deletion) must reproduce them byte-for-byte: same rules, same names, same
idx/parent_idx/level order, same exact heterogeneity floats, same `show()`
bytes. Do not regenerate these literals during the refactor — they ARE the
behavior being preserved.
"""

import io
from contextlib import redirect_stdout

import numpy as np

import effector
from effector.space_partitioning import Best, BestLevelWise

AXIS_LIMITS = np.array([[0, 10], [0, 10], [0, 10]]).T
FEATURE_NAMES = ["x1", "x2", "x3"]


def _toy_four_regions():
    """Four groups defined by thresholds on feature 1 (1.5 / 3 / 5) — the
    test_unit_space_partitioning toy, verbatim."""
    np.random.seed(0)
    N, D = 1000, 3
    X = np.random.uniform(0, 10, size=(N, D))
    y = np.empty(N, dtype=int)
    for i in range(N):
        if X[i, 1] < 3:
            y[i] = 0 if X[i, 1] < 1.5 else 1
        else:
            y[i] = 2 if X[i, 1] < 5 else 3
    return X, y


def _toy_categorical():
    """Heterogeneity fully explained by the binary categorical x3."""
    np.random.seed(0)
    N = 600
    X = np.stack(
        [
            np.random.uniform(0, 10, N),
            np.random.uniform(0, 10, N),
            np.random.randint(0, 2, N).astype(float),
        ],
        axis=1,
    )
    y = X[:, 2].astype(int)
    return X, y


def _raw_gini(y):
    def score(mask):
        labels = y[mask]
        _, counts = np.unique(labels, return_counts=True)
        p = counts / counts.sum()
        return 1 - np.sum(p**2)

    return score


def _find(finder, X, score_fn, *, feature=0, feature_types=None, ccf=(0, 1, 2)):
    return finder.find_regions(
        feature=feature,
        data=X,
        score_fn=score_fn,
        axis_limits=AXIS_LIMITS,
        feature_types=feature_types,
        cat_limit=10,
        candidate_conditioning_features=list(ccf),
        feature_names=FEATURE_NAMES,
        target_name="y",
    )


def _gated_data(n=500, seed=21):
    rng = np.random.default_rng(seed)
    return np.stack(
        [
            rng.uniform(-1, 1, n),
            rng.uniform(-1, 1, n),
            rng.integers(0, 2, n).astype(float),
        ],
        axis=1,
    )


def _gated_model(x):
    y = np.zeros_like(x[:, 0])
    ind = np.logical_and(x[:, 1] > 0, x[:, 2] == 0)
    y[ind] = 5 * x[ind, 0]
    return y


def _captured_show(part):
    buf = io.StringIO()
    with redirect_stdout(buf):
        part.show()
    return buf.getvalue()


# --------------------------------------------------------------------------
# expected literals (generated from the pre-refactor finders — do not edit)
# --------------------------------------------------------------------------

EXPECTED_BEST_FOUR_REGIONS = {
    "schema_version": 2,
    "feature": 0,
    "feature_name": "x1",
    "feature_names": ["x1", "x2", "x3"],
    "finder": "best",
    "regions": [
        {
            "idx": 0,
            "name": "x1",
            "rule": {"conditions": []},
            "heterogeneity": 0.666046,
            "nof_instances": 1000,
            "weight": 1.0,
            "level": 0,
            "parent_idx": None,
        },
        {
            "idx": 1,
            "name": "x1 | x2 < 5.00",
            "rule": {
                "conditions": [
                    {
                        "feature": 1,
                        "kind": "interval",
                        "lo": None,
                        "hi": 5.0,
                        "lo_closed": False,
                        "hi_closed": False,
                    }
                ]
            },
            "heterogeneity": 0.6615431811028641,
            "nof_instances": 501,
            "weight": 0.501,
            "level": 1,
            "parent_idx": 0,
        },
        {
            "idx": 2,
            "name": "x1 | x2 < 3.00",
            "rule": {
                "conditions": [
                    {
                        "feature": 1,
                        "kind": "interval",
                        "lo": None,
                        "hi": 3.0,
                        "lo_closed": False,
                        "hi_closed": False,
                    }
                ]
            },
            "heterogeneity": 0.4997366299381887,
            "nof_instances": 305,
            "weight": 0.305,
            "level": 2,
            "parent_idx": 1,
        },
        {
            "idx": 3,
            "name": "x1 | 3.00 ≤ x2 < 5.00",
            "rule": {
                "conditions": [
                    {
                        "feature": 1,
                        "kind": "interval",
                        "lo": 3.0,
                        "hi": 5.0,
                        "lo_closed": True,
                        "hi_closed": False,
                    }
                ]
            },
            "heterogeneity": 0.0,
            "nof_instances": 196,
            "weight": 0.196,
            "level": 2,
            "parent_idx": 1,
        },
        {
            "idx": 4,
            "name": "x1 | x2 ≥ 5.00",
            "rule": {
                "conditions": [
                    {
                        "feature": 1,
                        "kind": "interval",
                        "lo": 5.0,
                        "hi": None,
                        "lo_closed": True,
                        "hi_closed": False,
                    }
                ]
            },
            "heterogeneity": 0.0,
            "nof_instances": 499,
            "weight": 0.499,
            "level": 1,
            "parent_idx": 0,
        },
    ],
}

EXPECTED_BLW_FOUR_REGIONS = {
    "schema_version": 2,
    "feature": 0,
    "feature_name": "x1",
    "feature_names": ["x1", "x2", "x3"],
    "finder": "",
    "regions": [
        {
            "idx": 0,
            "name": "x1",
            "rule": {"conditions": []},
            "heterogeneity": 0.666046,
            "nof_instances": 1000,
            "weight": 1.0,
            "level": 0,
            "parent_idx": None,
        },
        {
            "idx": 1,
            "name": "x1 | x2 < 5.00",
            "rule": {
                "conditions": [
                    {
                        "feature": 1,
                        "kind": "interval",
                        "lo": None,
                        "hi": 5.0,
                        "lo_closed": False,
                        "hi_closed": False,
                    }
                ]
            },
            "heterogeneity": 0.6615431811028641,
            "nof_instances": 501,
            "weight": 0.501,
            "level": 1,
            "parent_idx": 0,
        },
        {
            "idx": 2,
            "name": "x1 | x2 ≥ 5.00",
            "rule": {
                "conditions": [
                    {
                        "feature": 1,
                        "kind": "interval",
                        "lo": 5.0,
                        "hi": None,
                        "lo_closed": True,
                        "hi_closed": False,
                    }
                ]
            },
            "heterogeneity": 0.0,
            "nof_instances": 499,
            "weight": 0.499,
            "level": 1,
            "parent_idx": 0,
        },
    ],
}

EXPECTED_BEST_CATEGORICAL = {
    "schema_version": 2,
    "feature": 0,
    "feature_name": "x1",
    "feature_names": ["x1", "x2", "x3"],
    "finder": "best",
    "regions": [
        {
            "idx": 0,
            "name": "x1",
            "rule": {"conditions": []},
            "heterogeneity": 0.4979944444444445,
            "nof_instances": 600,
            "weight": 1.0,
            "level": 0,
            "parent_idx": None,
        },
        {
            "idx": 1,
            "name": "x1 | x3 = 0.00",
            "rule": {"conditions": [{"feature": 2, "kind": "levels", "levels": [0.0]}]},
            "heterogeneity": 0.0,
            "nof_instances": 281,
            "weight": 0.4683333333333333,
            "level": 1,
            "parent_idx": 0,
        },
        {
            "idx": 2,
            "name": "x1 | x3 = 1.00",
            "rule": {"conditions": [{"feature": 2, "kind": "levels", "levels": [1.0]}]},
            "heterogeneity": 0.0,
            "nof_instances": 319,
            "weight": 0.5316666666666666,
            "level": 1,
            "parent_idx": 0,
        },
    ],
}

EXPECTED_GATED_PDP = {
    "schema_version": 2,
    "feature": 0,
    "feature_name": "x_0",
    "feature_names": ["x_0", "x_1", "x_2"],
    "finder": "best",
    "regions": [
        {
            "idx": 0,
            "name": "x_0",
            "rule": {"conditions": []},
            "heterogeneity": 1.2391190727630477,
            "nof_instances": 500,
            "weight": 1.0,
            "level": 0,
            "parent_idx": None,
        },
        {
            "idx": 1,
            "name": "x_0 | x_2 = 0.00",
            "rule": {"conditions": [{"feature": 2, "kind": "levels", "levels": [0.0]}]},
            "heterogeneity": 1.384029449043207,
            "nof_instances": 244,
            "weight": 0.488,
            "level": 1,
            "parent_idx": 0,
        },
        {
            "idx": 2,
            "name": "x_0 | x_2 = 0.00 and x_1 < -0.00",
            "rule": {
                "conditions": [
                    {"feature": 2, "kind": "levels", "levels": [0.0]},
                    {
                        "feature": 1,
                        "kind": "interval",
                        "lo": None,
                        "hi": -1.0396698700398943e-05,
                        "lo_closed": False,
                        "hi_closed": False,
                    },
                ]
            },
            "heterogeneity": 0.0,
            "nof_instances": 121,
            "weight": 0.242,
            "level": 2,
            "parent_idx": 1,
        },
        {
            "idx": 3,
            "name": "x_0 | x_2 = 0.00 and x_1 ≥ -0.00",
            "rule": {
                "conditions": [
                    {"feature": 2, "kind": "levels", "levels": [0.0]},
                    {
                        "feature": 1,
                        "kind": "interval",
                        "lo": -1.0396698700398943e-05,
                        "hi": None,
                        "lo_closed": True,
                        "hi_closed": False,
                    },
                ]
            },
            "heterogeneity": 4.308359250361119e-15,
            "nof_instances": 123,
            "weight": 0.246,
            "level": 2,
            "parent_idx": 1,
        },
        {
            "idx": 4,
            "name": "x_0 | x_2 = 1.00",
            "rule": {"conditions": [{"feature": 2, "kind": "levels", "levels": [1.0]}]},
            "heterogeneity": 0.0,
            "nof_instances": 256,
            "weight": 0.512,
            "level": 1,
            "parent_idx": 0,
        },
    ],
}

EXPECTED_GATED_PDP_MASK_SUMS = [500, 244, 121, 123, 256]

EXPECTED_GATED_PDP_SHOW = (
    "\n"
    "\n"
    "Feature 0 - Full partition tree:\n"
    "🌳 Full Tree Structure:\n"
    "───────────────────────\n"
    "x_0 🔹 [id: 0 | heter: 1.24 | inst: 500 | w: 1.00]\n"
    "    x_2 = 0.00 🔹 [id: 1 | heter: 1.38 | inst: 244 | w: 0.49]\n"
    "        x_1 < -0.00 🔹 [id: 2 | heter: 0.00 | inst: 121 | w: 0.24]\n"
    "        x_1 ≥ -0.00 🔹 [id: 3 | heter: 0.00 | inst: 123 | w: 0.25]\n"
    "    x_2 = 1.00 🔹 [id: 4 | heter: 0.00 | inst: 256 | w: 0.51]\n"
    "--------------------------------------------------\n"
    "Feature 0 - Statistics per tree level:\n"
    "🌳 Tree Summary:\n"
    "─────────────────\n"
    "Level 0🔹heter: 1.24\n"
    "    Level 1🔹heter: 0.68 | 🔻0.56 (45.49%)\n"
    "        Level 2🔹heter: 0.00 | 🔻0.68 (100.00%)\n"
    "\n"
    "\n"
)

EXPECTED_ROOT_ONLY_BEST = {
    "schema_version": 2,
    "feature": 0,
    "feature_name": "x1",
    "feature_names": ["x1", "x2", "x3"],
    "finder": "best",
    "regions": [
        {
            "idx": 0,
            "name": "x1",
            "rule": {"conditions": []},
            "heterogeneity": 0.666046,
            "nof_instances": 1000,
            "weight": 1.0,
            "level": 0,
            "parent_idx": None,
        }
    ],
}

EXPECTED_ROOT_ONLY_BEST_SHOW = (
    "\n"
    "\n"
    "Feature 0 - Full partition tree:\n"
    "No splits found for feature 0\n"
    "--------------------------------------------------\n"
    "Feature 0 - Statistics per tree level:\n"
    "No splits found for feature 0\n"
    "\n"
    "\n"
)

EXPECTED_ROOT_ONLY_BLW_CAT_FOI = {
    "schema_version": 2,
    "feature": 2,
    "feature_name": "x3",
    "feature_names": ["x1", "x2", "x3"],
    "finder": "",
    "regions": [
        {
            "idx": 0,
            "name": "x3",
            "rule": {"conditions": []},
            "heterogeneity": 0.4979944444444445,
            "nof_instances": 600,
            "weight": 1.0,
            "level": 0,
            "parent_idx": None,
        }
    ],
}

EXPECTED_TIE_BREAK = {
    "schema_version": 2,
    "feature": 0,
    "feature_name": "x1",
    "feature_names": ["x1", "x2", "x3"],
    "finder": "best",
    "regions": [
        {
            "idx": 0,
            "name": "x1",
            "rule": {"conditions": []},
            "heterogeneity": 1.0,
            "nof_instances": 1000,
            "weight": 1.0,
            "level": 0,
            "parent_idx": None,
        },
        {
            "idx": 1,
            "name": "x1 | x2 < 0.50",
            "rule": {
                "conditions": [
                    {
                        "feature": 1,
                        "kind": "interval",
                        "lo": None,
                        "hi": 0.5,
                        "lo_closed": False,
                        "hi_closed": False,
                    }
                ]
            },
            "heterogeneity": 1.0,
            "nof_instances": 59,
            "weight": 0.059,
            "level": 1,
            "parent_idx": 0,
        },
        {
            "idx": 2,
            "name": "x1 | x2 ≥ 0.50",
            "rule": {
                "conditions": [
                    {
                        "feature": 1,
                        "kind": "interval",
                        "lo": 0.5,
                        "hi": None,
                        "lo_closed": True,
                        "hi_closed": False,
                    }
                ]
            },
            "heterogeneity": 1.0,
            "nof_instances": 941,
            "weight": 0.941,
            "level": 1,
            "parent_idx": 0,
        },
    ],
}


# --------------------------------------------------------------------------
# tests
# --------------------------------------------------------------------------


def test_golden_best_four_regions():
    X, y = _toy_four_regions()
    part = _find(Best(max_depth=2, min_samples_leaf=50), X, _raw_gini(y))
    assert part.to_dict() == EXPECTED_BEST_FOUR_REGIONS


def test_golden_best_level_wise_four_regions():
    X, y = _toy_four_regions()
    part = _find(BestLevelWise(max_depth=2, min_samples_leaf=50), X, _raw_gini(y))
    assert part.to_dict() == EXPECTED_BLW_FOUR_REGIONS


def test_golden_best_categorical_conditioning():
    X, y = _toy_categorical()
    part = _find(
        Best(max_depth=1, heter_small_enough=0.0),
        X,
        _raw_gini(y),
        feature_types=["cont", "cont", "cat"],
    )
    assert part.to_dict() == EXPECTED_BEST_CATEGORICAL


def test_golden_gated_pdp_end_to_end():
    data = _gated_data()
    fx = effector.PDP(data, _gated_model, nof_instances="all")
    fx.fit(0, centering=False)
    part = fx.find_regions(0, finder=Best(max_depth=2))
    assert part.to_dict() == EXPECTED_GATED_PDP
    assert [int(r.mask.sum()) for r in part] == EXPECTED_GATED_PDP_MASK_SUMS
    assert _captured_show(part) == EXPECTED_GATED_PDP_SHOW


def test_golden_root_only_best():
    X, y = _toy_four_regions()
    part = _find(
        Best(min_heterogeneity_decrease_pcg=1000.0, heter_small_enough=0.0),
        X,
        _raw_gini(y),
    )
    assert part.to_dict() == EXPECTED_ROOT_ONLY_BEST
    assert _captured_show(part) == EXPECTED_ROOT_ONLY_BEST_SHOW


def test_golden_root_only_best_level_wise_categorical_foi():
    X, y = _toy_categorical()
    part = _find(
        BestLevelWise(search_partitions_when_categorical=False),
        X,
        _raw_gini(y),
        feature=2,
        feature_types=["cont", "cont", "cat"],
        ccf=(0, 1),
    )
    assert part.to_dict() == EXPECTED_ROOT_ONLY_BLW_CAT_FOI


def test_golden_tie_break_first_candidate_wins():
    """Constant score => every candidate ties; the accepted split must stay
    the first enumerated one (ccf order x ascending positions) after the
    matrix -> flat-list rewrite."""
    X, _ = _toy_four_regions()
    part = _find(
        Best(max_depth=1, min_heterogeneity_decrease_pcg=-1.0),
        X,
        lambda mask: 1.0,
        ccf=(1, 2),
    )
    assert part.to_dict() == EXPECTED_TIE_BREAK
