name: Execute all tests

on: [push, pull_request]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Run tests with coverage
        run: uv run --python 3.10 --no-default-groups --group test pytest --cov=effector --cov-report=xml tests -m "not slow"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: givasile/effector
